### ISSUE TITLE
Use TLS 1.2 ciphers to obtain ssllabs A+ rating

### ISSUE THREAD

**Issue by simonmittag** [simonmittag/jabba#21]
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256

![image](https://user-images.githubusercontent.com/7231277/82140787-a5973580-9874-11ea-9a22-43552e2d91e1.png)

**Comment by danieltigse** [comment]
Could you share your `tls.ini` file?

**Comment by simonmittag** [comment]
Hi Daniel, TLS support is officially coming out in the next release (v0.6). I'll provide a sample config with it.
